SELECT X.*
FROM 
    (
        SELECT
            RT.*
        FROM DE_CLIENTES_NILO CL
        RIGHT JOIN DE_RETROATIVOS_NILO RT
        ON CL.ID_CLIENTE = RT.ID_CLIENTE AND CL.CD_PRODUTO = RT.CD_PRODUTO 
    ) X
WHERE X.ID_CLIENTE = 
