SELECT  CL.ID_CLIENTE
        ,CL.TEL_CELULAR
        ,CL.NOME
        ,'PT-BR' AS LOCALE
        ,PT.URL_PRODUTO
        ,PT.MS
        ,PD.DESC_PRODUTO
        ,PD.DESC_PROD_DETALHADA
        ,PD.DESC_CLASSIF_PRODUTO
        ,DB.DT_HR_VENDA 
        ,DB.CD_PRODUTO
        ,DB.DATA_BASE
        ,DB.DT_PRIMEIRO_LEMBRETE
        ,DB.DT_SEGUNDO_LEMBRETE
        ,DB.DATA_RESGATE
FROM DE_CAD_CLIENTE_RAIA CL
INNER JOIN DE_CRONICOS_DATA_BASE DB
ON DB.ID_CLIENTE = CL.ID_CLIENTE
INNER JOIN DE_PRODUTOS_RAIA PT
ON DB.CD_PRODUTO = PT.CD_PRODUTO
INNER JOIN ent.DE_CAD_PRODUTO PD
ON PT.CD_PRODUTO = PD.CD_PRODUTO
WHERE CL.TEL_CELULAR IS NOT NULL 
AND PT.CD_PRODUTO IS NOT NULL
AND NOT EXISTS 
(
        SELECT 1
        FROM ent.DE_BLACKLIST_CRONICOS CR
        WHERE CR.CD_PRODUTO = PT.CD_PRODUTO
)