  SELECT 
        Y.ID_CLIENTE
        ,Y.CD_PRODUTO
        ,Y.NR_DURACAO_CAIXA
        ,Y.DT_HR_VENDA
        ,Y.QTD_DO_ITEM
        ,CASE 
            WHEN CONVERT(DATE,Y.DT_HR_VENDA, 101) <= (SELECT CONVERT(DATE,UT.DATA_BASE, 101) FROM DE_DT_ULTIMA_COMPRA_CRONICOS UT WHERE Y.ID_CLIENTE = UT.ID_CLIENTE AND Y.CD_PRODUTO = UT.CD_PRODUTO AND CONVERT(DATE,Y.DT_HR_VENDA, 101) > CONVERT(DATE,UT.DT_ULTIMA_COMPRA, 101)) THEN (SELECT U.DT_ULTIMA_COMPRA FROM DE_DT_ULTIMA_COMPRA_CRONICOS U WHERE Y.ID_CLIENTE = U.ID_CLIENTE AND Y.CD_PRODUTO = U.CD_PRODUTO)
            ELSE Y.DT_HR_VENDA
        END AS DT_VENDA
        ,CASE 
            WHEN CONVERT(DATE,Y.DT_HR_VENDA, 101) <= (SELECT CONVERT(DATE,CR.DATA_BASE, 101) FROM DE_DT_ULTIMA_COMPRA_CRONICOS CR WHERE Y.ID_CLIENTE = CR.ID_CLIENTE AND Y.CD_PRODUTO = CR.CD_PRODUTO AND CONVERT(DATE,Y.DT_HR_VENDA, 101) > CONVERT(DATE,CR.DT_ULTIMA_COMPRA, 101)) THEN ((SELECT H.QTD_DO_ITEM FROM DE_DT_ULTIMA_COMPRA_CRONICOS H WHERE Y.ID_CLIENTE = H.ID_CLIENTE AND Y.CD_PRODUTO = H.CD_PRODUTO) + Y.QTD_DO_ITEM)
            ELSE Y.QTD_DO_ITEM
        END AS QTD_ITEM
FROM DE_FULL_COMPRADORES_CRONICOS_RAIA Y
WHERE Y.ID_CLIENTE = '157994472'