SELECT 
    A.ID_CLIENTE 
    ,B.CD_PRODUTO 
    ,CL.CD_FILIAL_FREQ AS cadCliente_CD_FILIAL_FREQ
FROM ent.DE_PRODUTO_TRATAMENTO C
INNER JOIN  DE_NOTA_ITEM_RAIA B
ON B.CD_PRODUTO = C.CD_PRODUTO
INNER JOIN DE_NOTA_HEADER_RAIA A
ON A.ID_NF = B.ID_NF
INNER JOIN  DE_CAD_CLIENTE_RAIA CL
ON A.ID_CLIENTE = CL.ID_CLIENTE
WHERE CONVERT(DATE,B.DT_HR_VENDA, 101) = CONVERT(DATE,GETDATE()-1, 101)
AND NOT EXISTS
(
    SELECT FL.*
    FROM DE_FULL_COMPRADORES_CRONICOS_RAIA FL
    WHERE FL.ID_CLIENTE = A.ID_CLIENTE 
    AND CONVERT(DATE,FL.DT_HR_VENDA, 101) >= CONVERT(DATE,GETDATE()-365, 101)
)