
SELECT 
    CR.ID_CLIENTE
    ,CR.CD_PRODUTO
    ,CR.DT_HR_VENDA
    ,CR.DT_PRIMEIRO_LEMBRETE
    ,CR.DT_SEGUNDO_LEMBRETE
    ,CR.DATA_RESGATE
    ,CR.DATA_BASE
    ,CL.TEL_CELULAR
    ,CL.NOME
    ,'PT-BR' AS LOCALE
    ,PT.URL_PRODUTO
    ,PT.MS
    ,PD.DESC_PRODUTO
    ,PD.DESC_PROD_DETALHADA
    ,PD.DESC_CLASSIF_PRODUTO
FROM DE_CRONICOS_LEMBRETE_HOJE CR
INNER JOIN  DE_CAD_CLIENTE_RAIA CL
ON CR.ID_CLIENTE = CL.ID_CLIENTE
INNER JOIN DE_PRODUTOS_RAIA PT
ON CR.CD_PRODUTO = PT.CD_PRODUTO
INNER JOIN ent.DE_CAD_PRODUTO PD
ON PT.CD_PRODUTO = PD.CD_PRODUTO
WHERE CL.TEL_CELULAR IS NOT NULL 
AND PT.CD_PRODUTO IS NOT NULL
AND NOT EXISTS 
(
        SELECT 1
        FROM ent.DE_BLACKLIST_CRONICOS CR
        WHERE CR.CD_PRODUTO = PT.CD_PRODUTO
)