SELECT ID_NF, VL_PMC, VL_UNITARIO, DESC_ITEM, CD_PRODUTO, QTD_DO_ITEM, DESC_PBM, CD_TIPO_DE_DESCONTO, DESC_TIPO_DE_DESCONTO, DT_HR_VENDA, NR_NF_ITEM
,ltrim(FORMAT(NR_PROMOCIONAL, '00000000000000')) AS NR_PROMOCIONAL
FROM DE_NOTA_ITEM_DROGASIL_OLD_TESTE



SELECT 
    CD_CAMPANHA_OFERTA, DS_CAMPANHA_OFERTA, CD_LOGOMARCA, CD_CAMPANHA_ACAO, CD_CAMPANHA_STATUS, CD_CAMPANHA_CANAL, CD_GRUPO, CD_CATEGORIA, CD_GRUPO_REMARCACAO, CD_PRODUTO, PC_DESCONTO, CD_CAMPANHA_OFERTA_POOL, DT_INICIO, DT_FIM, FL_ATIVO
,ltrim(FORMAT(X.NR_PROMOCIONAL_INT, '00000000000000')) AS NR_PROMOCIONAL
FROM
    (
        SELECT CD_CAMPANHA_OFERTA, DS_CAMPANHA_OFERTA, CD_LOGOMARCA, CD_CAMPANHA_ACAO, CD_CAMPANHA_STATUS, CD_CAMPANHA_CANAL, CD_GRUPO, CD_CATEGORIA, CD_GRUPO_REMARCACAO, CD_PRODUTO, PC_DESCONTO, CD_CAMPANHA_OFERTA_POOL, DT_INICIO, DT_FIM, FL_ATIVO
        ,CONVERT(BIGINT, NR_PROMOCIONAL) AS NR_PROMOCIONAL_INT
        FROM DE_CAMP_OFERTA_RAIA
    ) X



SELECT 
    CD_CAMPANHA_OFERTA, DS_CAMPANHA_OFERTA, CD_LOGOMARCA, CD_CAMPANHA_ACAO, CD_CAMPANHA_STATUS, CD_CAMPANHA_CANAL, CD_GRUPO, CD_CATEGORIA, CD_GRUPO_REMARCACAO, CD_PRODUTO, PC_DESCONTO, CD_CAMPANHA_OFERTA_POOL, DT_INICIO, DT_FIM, FL_ATIVO
, NR_PROMOCIONAL, LEN(NR_PROMOCIONAL) AS COUNT_NR_PROMO
FROM DE_CAMP_OFERTA_RAIA








