SELECT 
    X.ID_CLIENTE
    ,X.CD_FILIAL_FREQ
    ,X.CD_PRODUTO
FROM
(
    SELECT 
        A.ID_CLIENTE 
        ,CL.CD_FILIAL_FREQ 
        ,A.CD_PRODUTO
        ,row_number() over(partition by CL.CD_FILIAL_FREQ order by A.ID_CLIENTE desc) as RowNumber
    FROM DE_DR_REL_ANIVERSARIO20208R_TMKT_1 A
    INNER JOIN DE_CAD_CLIENTE_RAIA CL 
    ON A.ID_CLIENTE = CL.ID_CLIENTE
    INNER JOIN ENT.DE_CAD_FILIAL DCF
    ON DCF.CD_FILIAL = CL.CD_FILIAL_FREQ
    WHERE CL.CD_FILIAL_FREQ IS NOT NULL
    AND DCF.FL_TERMINAL_CONSULTA = 1
    AND DCF.BANDEIRA LIKE '%RAIA%' 
    AND NOT EXISTS 
    (
        SELECT 1 
        FROM ENT.DE_CAD_DONOTCALL DCN
        WHERE DCN.DDD_TELEFONE = CL.TEL_CELULAR
    )
) X
WHERE X.RowNumber <= 100