
    SELECT A.ID_CLIENTE, A.NOME_COMPLETO, A.EMAIL, 
    CASE
        WHEN A.FLAG IS NULL THEN 'ABANDONOU'
    END AS FLAG,
    CASE 
        WHEN A.EMAIL LIKE '%@hotmail%' THEN 'MICROSOFT'            
        WHEN A.EMAIL LIKE '%@outlook%' THEN 'MICROSOFT'
        WHEN A.EMAIL LIKE '%@msn%' THEN 'MICROSOFT'    
        WHEN A.EMAIL LIKE '%@gmail%' THEN 'GMAIL'
        WHEN A.EMAIL LIKE '%@yahoo%' THEN 'YAHOO'
        ELSE 'OUTROS'
    END AS DOMINIO
    FROM DE_WARMUP_DROGASIL_ABANDONOU A

    UNION

    SELECT B.ID_CLIENTE, B.NOME_COMPLETO, B.EMAIL,
    CASE
        WHEN B.FLAG IS NULL THEN 'DESCOMPROMISSADO'
    END AS FLAG,
    CASE 
        WHEN B.EMAIL LIKE '%@hotmail%' THEN 'MICROSOFT'            
        WHEN B.EMAIL LIKE '%@outlook%' THEN 'MICROSOFT'
        WHEN B.EMAIL LIKE '%@msn%' THEN 'MICROSOFT'    
        WHEN B.EMAIL LIKE '%@gmail%' THEN 'GMAIL'
        WHEN B.EMAIL LIKE '%@yahoo%' THEN 'YAHOO'
        ELSE 'OUTROS'
    END AS DOMINIO
    FROM DE_WARMUP_DROGASIL_DESCOMPROMISSADO B

    UNION

    SELECT C.ID_CLIENTE, C.NOME_COMPLETO, C.EMAIL, 
    CASE
        WHEN C.FLAG IS NULL THEN 'EMABANDONO'
    END AS FLAG,
    CASE 
        WHEN C.EMAIL LIKE '%@hotmail%' THEN 'MICROSOFT'            
        WHEN C.EMAIL LIKE '%@outlook%' THEN 'MICROSOFT'
        WHEN C.EMAIL LIKE '%@msn%' THEN 'MICROSOFT'    
        WHEN C.EMAIL LIKE '%@gmail%' THEN 'GMAIL'
        WHEN C.EMAIL LIKE '%@yahoo%' THEN 'YAHOO'
        ELSE 'OUTROS'
    END AS DOMINIO
    FROM DE_WARMUP_DROGASIL_EMABANDONO C

    UNION 

    SELECT D.ID_CLIENTE, D.NOME_COMPLETO, D.EMAIL, 
    CASE
        WHEN D.FLAG IS NULL THEN 'POTENCIAL'
    END AS FLAG,
    CASE 
        WHEN D.EMAIL LIKE '%@hotmail%' THEN 'MICROSOFT'            
        WHEN D.EMAIL LIKE '%@outlook%' THEN 'MICROSOFT'
        WHEN D.EMAIL LIKE '%@msn%' THEN 'MICROSOFT'    
        WHEN D.EMAIL LIKE '%@gmail%' THEN 'GMAIL'
        WHEN D.EMAIL LIKE '%@yahoo%' THEN 'YAHOO'
        ELSE 'OUTROS'
    END AS DOMINIO
    FROM DE_WARMUP_DROGASIL_POTENCIAL D

    UNION 

    SELECT E.ID_CLIENTE, E.NOME_COMPLETO, E.EMAIL, 
    CASE
        WHEN E.FLAG IS NULL THEN 'PREMIUM'
    END AS FLAG,
    CASE 
        WHEN E.EMAIL LIKE '%@hotmail%' THEN 'MICROSOFT'            
        WHEN E.EMAIL LIKE '%@outlook%' THEN 'MICROSOFT'
        WHEN E.EMAIL LIKE '%@msn%' THEN 'MICROSOFT'    
        WHEN E.EMAIL LIKE '%@gmail%' THEN 'GMAIL'
        WHEN E.EMAIL LIKE '%@yahoo%' THEN 'YAHOO'
        ELSE 'OUTROS'
    END AS DOMINIO
    FROM DE_WARMUP_DROGASIL_PREMIUM E

    UNION 

    SELECT F.ID_CLIENTE, F.NOME_COMPLETO, F.EMAIL, 
    CASE
        WHEN F.FLAG IS NULL THEN 'VALIOSO'
    END AS FLAG,
    CASE 
        WHEN F.EMAIL LIKE '%@hotmail%' THEN 'MICROSOFT'            
        WHEN F.EMAIL LIKE '%@outlook%' THEN 'MICROSOFT'
        WHEN F.EMAIL LIKE '%@msn%' THEN 'MICROSOFT'    
        WHEN F.EMAIL LIKE '%@gmail%' THEN 'GMAIL'
        WHEN F.EMAIL LIKE '%@yahoo%' THEN 'YAHOO'
        ELSE 'OUTROS'
    END AS DOMINIO
    FROM DE_WARMUP_DROGASIL_VALIOSO F



    