SELECT PHR.ID_CLIENTE
    ,PHR.TEL_CELULAR
    ,PHR.FLAG_PRECO
    ,PHR.VALOR_TOTAL_NF
    ,PHR.DATA_HORA_VENDA
    ,PHR.DATA_CADASTRO
    ,PHR.CARTAO
    ,PHR.TIPO_CADASTRO
    ,PHR.FILIAL_CADASTRO
    ,PHR.CADASTRO_WEB
    ,PHR.EMAIL
    ,PHR.NOME
    ,PHR.NR_PROMOCIONAL_BV
    ,PHR.NR_PROMOCIONAL_OT
    ,PHR.NR_PROMOCIONAL_VC
    ,PHR.NR_PROMOCIONAL_VR
    ,PHR.CD_CAMPANHA_OFERTA_RAIA_BV
    ,PHR.CD_CAMPANHA_OFERTA_RAIA_OT
    ,PHR.CD_CAMPANHA_OFERTA_RAIA_VC
    ,PHR.CD_CAMPANHA_OFERTA_RAIA_VR
    ,PHR.LOCALE
    ,PHR.FL_STEP
    ,PHR.DT_STEP
    ,PHR.OPT_OUT
    ,PHR.DT_OFERTA_TURBINADA
    ,PHR.DT_VOUCHER
    ,PHR.DT_VOUCHER_REPIQUE
    ,PHR.FLAG_GC
FROM DE_NOVOS_POTENCIAIS_RAIA PHR
WHERE NOT EXISTS
(
    SELECT 1
    FROM DE_ALL_NOVOS_POTENCIAIS_RAIA ANP
    WHERE PHR.ID_CLIENTE = ANP.ID_CLIENTE
) 