SELECT
    PTR.ID_CLIENTE
    ,3 as CD_CAMPANHA_SECAO    
    ,1 AS CD_CAMPANHA_STATUS
    ,1 AS NR_PRIORIDADE_SECAO
    ,1 AS FL_ATIVO
    ,8 AS CD_CAMPANHA_CANAL
    ,1 AS CD_LOGOMARCA
    ,999 AS CD_CAMPANHA_OFERTA_POOL
    ,PTR.NR_PROMOCIONAL_BV AS NR_PROMOCIONAL
    ,PTR.CD_CAMPANHA_OFERTA_RAIA_BV AS CD_CAMPANHA_OFERTA
    ,PTR.FILIAL_CADASTRO AS CD_FILIAL
    ,CONVERT(VARCHAR,GETDATE(), 103) AS DT_INICIO
    ,CONVERT(VARCHAR,GETDATE()+10, 103) AS DT_FIM
FROM DE_NOVOS_POTENCIAIS_RAIA PTR
WHERE PTR.NR_PROMOCIONAL_BV IS NOT NULL
AND NOT EXISTS
(
    SELECT 1 
    FROM DE_NOVOS_POTENCIAIS_HISTORICO_RAIA NPH
    WHERE PTR.ID_CLIENTE = NPH.ID_CLIENTE
)