SELECT PPR.* 
    ,CONVERT(DATE, GETDATE(), 120) AS DT_ENVIO_RD
FROM DE_NOVOS_POTENCIAIS_RAIA PPR
WHERE NOT EXISTS
(
    SELECT 1 
    FROM DE_NOVOS_POTENCIAIS_HISTORICO_RAIA PTH
    WHERE PTH.ID_CLIENTE = PPR.ID_CLIENTE
)