SELECT X.*
FROM 
(
SELECT DISTINCT
    CCR.ID_CLIENTE
    ,CCR.EMAIL
    ,CCR.TEL_CELULAR
    ,CCR.DATA_CADASTRO
    ,CCR.NOME
    ,CCR.CADASTRO_WEB
    ,NTR.VALOR_TOTAL_NF
    ,'pt-BR' AS LOCALE
    ,TLR.CD_TELEVENDA
    ,NTR.ID_NF
    ,NTR.DATA_HORA_VENDA
    ,CONVERT(VARCHAR(10),GETDATE(), 101) AS DT_COMPRE_APP
    ,CONVERT(VARCHAR(10),GETDATE()+15, 101) AS DT_COMPRE_RETIRE
    ,CONVERT(VARCHAR(10),GETDATE()+30, 101) AS DT_CASHBACK
    ,CONVERT(VARCHAR(10),GETDATE()+45, 101) AS DT_REPIQUE
    ,row_number() over (partition by NTR.ID_CLIENTE order by NTR.DATA_HORA_VENDA asc) RANKING
FROM DE_CAD_CLIENTE_RAIA CCR
INNER JOIN DE_NOTA_HEADER_RAIA NTR
ON CCR.ID_CLIENTE = NTR.ID_CLIENTE
INNER JOIN DE_TELEVENDA_RAIA TLR
ON TLR.CD_TELEVENDA = NTR.CD_TELEVENDA
WHERE NOT EXISTS
(
    SELECT 1 
    FROM DE_ALL_CLIENTES_MULTICANAL_RAIA CMR
    WHERE CMR.ID_CLIENTE = CCR.ID_CLIENTE
)
AND (CONVERT(VARCHAR(10),NTR.DATA_HORA_VENDA, 101) BETWEEN CONVERT(VARCHAR(10),GETDATE()-30, 101) AND CONVERT(VARCHAR(10),GETDATE()-1, 101))
AND (CCR.EMAIL IS NOT NULL OR CCR.TEL_CELULAR IS NOT NULL)
) X
WHERE EXISTS (

    SELECT TTR.ID_CLIENTE
    FROM DE_TELEVENDA_RAIA TTR
    WHERE TTR.ID_CLIENTE = X.ID_CLIENTE
    GROUP BY TTR.ID_CLIENTE
    HAVING COUNT(TTR.ID_CLIENTE) = 1
)
AND RANKING = 1
