SELECT
    X.ID_CLIENTE
    ,X.DATA_HORA_VENDA
    ,X.VALOR_TOTAL_NF
    ,X.ID_NF
    ,X.CD_TELEVENDA
FROM (
    SELECT
        CMR.ID_CLIENTE
        ,NTH.DATA_HORA_VENDA
        ,NTH.VALOR_TOTAL_NF
        ,NTH.ID_NF
        ,TLR.CD_TELEVENDA
        ,row_number() over(partition by CMR.ID_CLIENTE order by NTH.DATA_HORA_VENDA desc) as RowNumber
        FROM DE_ALL_CLIENTES_MULTICANAL_RAIA CMR
        INNER JOIN DE_NOTA_HEADER_RAIA NTH
        ON CMR.ID_CLIENTE = NTH.ID_CLIENTE
        INNER JOIN DE_TELEVENDA_RAIA TLR
        ON TLR.CD_TELEVENDA = NTH.CD_TELEVENDA
)X
WHERE RowNumber = 1