SELECT PHR.*
FROM DE_PRE_SEGMENTACAO_EX_FIEL_RAIA PHR
WHERE
EXISTS
(
    SELECT DLP.STATUS
    FROM ENT.DE_LOG_PRICING DLP
    WHERE DATEDIFF(minute, CONVERT(varchar(16),DLP.DATA_HORA_PROCESSAMENTO,120), CONVERT(varchar(16),GETDATE(),120) ) <= 15
    AND DLP.STATUS = 'SUCESSO'
    AND DLP.NOME_ARQUIVO LIKE '%DE_PRICING_DR_EX_FIEL%'
) 
AND NOT EXISTS
(
    SELECT 1
    FROM DE_ALL_EX_FIEL_RAIA AEX
    WHERE AEX.ID_CLIENTE = PHR.ID_CLIENTE
)