SELECT PHR.ID_CLIENTE
       ,CCL.EMAIL   
       ,CCL.TEL_CELULAR
       ,CCL.NOME
       ,'PT-BR' AS LOCALE
       ,GETDATE() AS DT_JOURNEY
FROM ent.DE_DH_POTENCIAIS_DIGITAIS PHR
INNER JOIN DE_CAD_CLIENTE_RAIA CCL /*TROCAR PARA DE DE DROGASIL*/
ON CCL.ID_CLIENTE = PHR.ID_CLIENTE
WHERE 
NOT EXISTS
(
    SELECT 1
    FROM DE_BOUNCES_BLACKLIST_RAIA BBR /*TROCAR PARA DE DE DROGASIL*/
    WHERE BBR.ID_CLIENTE = CCL.ID_CLIENTE
)
AND NOT EXISTS
(
    SELECT 1
    FROM DE_NOTA_HEADER_RAIA NHR /*TROCAR PARA DE DE DROGASIL*/
    WHERE NHR.ID_CLIENTE = CCL.ID_CLIENTE AND (NHR.CD_TELEVENDA IS NOT NULL OR NHR.CD_TELEVENDA = 0)
)
AND NOT EXISTS
(
    SELECT 1
    FROM DE_ALL_POTENCIAIS_DIGITAIS_RAIA APD /*TROCAR PARA DE DE DROGASIL*/
    WHERE APD.ID_CLIENTE = PHR.ID_CLIENTE
)
AND (CCL.EMAIL IS NOT NULL OR CCL.TEL_CELULAR IS NOT NULL)
