SELECT TOP 100000
    GM2.EMAIL as EMAIL
    ,GM2.ID_CLIENTE AS ID_CLIENTE
    ,GM2.DOMINIO AS DOMINIO
    ,'5' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+26) as DATA_WARM
FROM FLT_DROGASIL_GMAIL_SHABIT GM2
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_DROGASIL_JOURNEY JR
    WHERE JR.EMAIL = GM2.EMAIL
)

UNION

SELECT TOP 160000
    MF2.EMAIL as EMAIL
    ,MF2.ID_CLIENTE AS ID_CLIENTE
    ,MF2.DOMINIO AS DOMINIO
    ,'5' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+26) as DATA_WARM
FROM FLT_DROGASIL_MICROSOFT_SHABIT MF2
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_DROGASIL_JOURNEY JR
    WHERE JR.EMAIL = MF2.EMAIL
)
