SELECT TOP 1943
    GM1.EmailAddress as EMAIL
    ,GM1.IdCliente AS ID_CLIENTE
    ,GM1.Dominio AS DOMINIO
    ,'1' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+6) as DATA_WARM
FROM FLT_DROGASIL_GMAIL_ENGAJADOS GM1
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_DROGASIL_JOURNEY JR
    WHERE JR.EMAIL = GM1.EmailAddress
)

UNION

SELECT TOP 2057
    GM2.EMAIL as EMAIL
    ,GM2.ID_CLIENTE AS ID_CLIENTE
    ,GM2.DOMINIO AS DOMINIO
    ,'1' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+6) as DATA_WARM
FROM FLT_DROGASIL_GMAIL_SHABIT GM2
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_DROGASIL_JOURNEY JR
    WHERE JR.EMAIL = GM2.EMAIL
)

UNION

SELECT TOP 5000
    MF1.EmailAddress as EMAIL
    ,MF1.IdCliente AS ID_CLIENTE
    ,MF1.Dominio AS DOMINIO
    ,'1' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+6) as DATA_WARM
FROM FLT_DROGASIL_MICROSOFT_ENGAJADOS MF1
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_DROGASIL_JOURNEY JR
    WHERE JR.EMAIL = MF1.EmailAddress
)

UNION

SELECT TOP 5000
    YH1.EmailAddress as EMAIL
    ,YH1.IdCliente AS ID_CLIENTE
    ,YH1.Dominio AS DOMINIO
    ,'1' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+6) as DATA_WARM
FROM FLT_DROGASIL_YAHOO_ENGAJADOS YH1
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_DROGASIL_JOURNEY JR
    WHERE JR.EMAIL = YH1.EmailAddress
)

UNION

SELECT TOP 5000
    OT1.EmailAddress as EMAIL
    ,OT1.IdCliente AS ID_CLIENTE
    ,OT1.Dominio AS DOMINIO
    ,'1' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+6) as DATA_WARM
FROM FLT_DROGASIL_OUTROS_ENGAJADOS OT1
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_DROGASIL_JOURNEY JR
    WHERE JR.EMAIL = OT1.EmailAddress
)
