SELECT 
    X.ID_CLIENTE
    ,X.CD_PRODUTO
    ,X.CD_FILIAL_FREQ
FROM (
    SELECT
    (
        CASE 
            WHEN 
            MONTH(GETDATE()) > MONTH(CCL.DATA_NASC)
            OR
            (
                MONTH(GETDATE()) = MONTH(CCL.DATA_NASC) 
                AND DAY(GETDATE()) >= DAY(CCL.DATA_NASC) 
            )
        THEN DATEDIFF(YEAR, CCL.DATA_NASC, GETDATE()) 
        ELSE DATEDIFF(YEAR, CCL.DATA_NASC, GETDATE()) -1 END
    ) AS IDADE
    ,ACR.ID_CLIENTE
    ,ACR.CD_PRODUTO
    ,ACR.DT_HR_VENDA
    ,ACR.FL_STEP
    ,ACR.DT_STEP
    ,CSG.DS_TP_SEGMENTACAO
    ,CSG.DS_SEGMENTACAO
    ,CSG.CD_TP_SEGMENTACAO
    ,CCL.CD_FILIAL_FREQ
    ,DCF.BANDEIRA
    ,DCF.FL_TERMINAL_CONSULTA
    ,row_number() over(partition by CCL.CD_FILIAL_FREQ order by CCL.NOME desc) as RowNumber
    FROM DE_ALL_CRONICOS_RAIA ACR
    INNER JOIN DE_CAD_CLIENTE_RAIA CCL
    ON ACR.ID_CLIENTE = CCL.ID_CLIENTE
    INNER JOIN ENT.DE_CAD_FILIAL DCF
    ON DCF.CD_FILIAL = CCL.CD_FILIAL_FREQ
    INNER JOIN ENT.DE_SEGMENTACAO_DH_SHABITS SDH
    ON ACR.ID_CLIENTE = SDH.ID_CLIENTE
    INNER JOIN ENT.DE_CAD_TP_SEGMENTACAO CSG
    ON SDH.CD_TP_SEGMENTACAO = CSG.CD_TP_SEGMENTACAO
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM ent.DE_CAD_DONOTCALL DNC
        WHERE DNC.DDD_TELEFONE = CCL.TEL_CELULAR
    )
)X
WHERE X.RowNumber <= 100
AND X.CD_TP_SEGMENTACAO IN (16,18)
AND X.IDADE >= 40
AND X.FL_STEP = 3
AND X.CD_FILIAL_FREQ IS NOT NULL
AND X.BANDEIRA LIKE '%RAIA%'
AND X.FL_TERMINAL_CONSULTA = 1
