SELECT 
    ACR.ID_CLIENTE
    ,ACR.TEL_CELULAR
    ,ACR.NOME
    ,ACR.LOCALE
    ,ACR.URL_PRODUTO
    ,ACR.DESC_PRODUTO
    ,ACR.CD_PRODUTO
    ,ACR.DT_HR_VENDA
    ,ACR.DESC_PROD_DETALHADA
    ,ACR.DESC_CLASSIF_PRODUTO
    ,ACR.MS
    ,ACR.DATA_BASE
    ,ACR.DT_PRIMEIRO_LEMBRETE
    ,ACR.DT_SEGUNDO_LEMBRETE
    ,ACR.DATA_RESGATE
    /*alterar os messageID para os corretos da Drogasil*/
    ,CASE
        WHEN SMS.MessageID = 316 AND ACR.DT_PRIMEIRO_LEMBRETE = CONVERT(VARCHAR(10), GETDATE(), 101) THEN 1
        WHEN SMS.MessageID = 317 AND ACR.DT_SEGUNDO_LEMBRETE = CONVERT(VARCHAR(10), GETDATE(), 101) THEN 2
        WHEN SMS.MessageID = 315 AND ACR.DATA_RESGATE = CONVERT(VARCHAR(10), GETDATE(), 101) THEN 3
        ELSE 0
    END AS FL_STEP
    ,CASE
        WHEN SMS.MessageID = 316 AND ACR.DT_PRIMEIRO_LEMBRETE = CONVERT(VARCHAR(10), GETDATE(), 101) THEN SMS.ActionDateTime
        WHEN SMS.MessageID = 317 AND ACR.DT_SEGUNDO_LEMBRETE = CONVERT(VARCHAR(10), GETDATE(), 101) THEN SMS.ActionDateTime
        WHEN SMS.MessageID = 315 AND ACR.DATA_RESGATE = CONVERT(VARCHAR(10), GETDATE(), 101) THEN SMS.ActionDateTime
        ELSE NULL
    END AS DT_STEP
/*alterar para a all de drogasil*/FROM DE_ALL_CRONICOS_RAIA ACR
INNER JOIN _smsmessagetracking SMS
ON ACR.TEL_CELULAR = SMS.Mobile
WHERE SMS.Delivered = 1
AND ( ACR.DT_PRIMEIRO_LEMBRETE = CONVERT(VARCHAR(10), GETDATE(), 101) OR ACR.DT_SEGUNDO_LEMBRETE = CONVERT(VARCHAR(10), GETDATE(), 101) OR ACR.DATA_RESGATE = CONVERT(VARCHAR(10), GETDATE(), 101) )
AND SMS.ActionDateTime >= CONVERT(VARCHAR(10), GETDATE()-30, 101)