SELECT
    PTR.ID_CLIENTE
    ,3 as CD_CAMPANHA_SECAO
    ,3 as CD_CAMPANHA_ACAO
    ,1 AS CD_CAMPANHA_STATUS
    ,1 AS NR_PRIORIDADE_SECAO
    ,1 AS FL_ATIVO
    ,8 AS CD_CAMPANHA_CANAL
    ,1 AS CD_LOGOMARCA
    ,999 AS CD_CAMPANHA_OFERTA_POOL
    ,'' AS NR_PROMOCIONAL
    ,'' AS CD_CAMPANHA_OFERTA
    ,'' AS VL_DESCONTO
    ,PTR.FILIAL_CADASTRO AS CD_FILIAL
    ,CONVERT(VARCHAR,GETDATE(), 103) AS DT_INICIO
    ,CONVERT(VARCHAR,GETDATE()+20, 103) AS DT_FIM
FROM DE_PRE_SEGMENTACAO_PROPENSOS_CHURN_RAIA PTR
