SELECT
    PTR.ID_CLIENTE
    ,3 as CD_CAMPANHA_SECAO    
    ,3 as CD_CAMPANHA_ACAO
    ,1 AS CD_CAMPANHA_STATUS
    ,1 AS NR_PRIORIDADE_SECAO
    ,1 AS FL_ATIVO
    ,8 AS CD_CAMPANHA_CANAL
    ,1 AS CD_LOGOMARCA/*1 PARA RAIA E 2 PARA DROGASIL*/
    ,999 AS CD_CAMPANHA_OFERTA_POOL/*999 PARA RAIA E 998 PARA DROGASIL*/
    ,'06000002101508' AS NR_PROMOCIONAL/*CHECAR NA DE_NR_CONSULTA PARA DIFERENTES BANDEIRAS*/
    ,'372800' AS CD_CAMPANHA_OFERTA/*CHECAR NA DE_NR_CONSULTA PARA DIFERENTES BANDEIRAS*/
    ,15 AS PC_DESCONTO/*CHECAR NA DE_NR_CONSULTA PARA DIFERENTES STEPS DA RÉGUA*/
    ,2 AS CD_GRUPO
    ,PTR.FILIAL_CADASTRO AS CD_FILIAL
    ,CONVERT(VARCHAR,GETDATE()+60, 103) AS DT_INICIO /*DT_INICIO DE ACORDO COM O DESENHO DA RÉGUA*/
    ,CONVERT(VARCHAR,GETDATE()+85, 103) AS DT_FIM /*DT_FIM DE ACORDO COM O DESENHO DA RÉGUA*/
FROM DE_PRE_SEGMENTACAO_PROPENSOS_CHURN_RAIA PTR /*CHECAR A DE PARA A RÉGUA*/
