SELECT PHR.*
FROM DE_PRE_SEGMENTACAO_PROPENSOS_CHURN_RAIA PHR
WHERE 
EXISTS
(
    SELECT DLP.STATUS
    FROM ENT.DE_LOG_PRICING DLP
    WHERE DATEDIFF(minute, CONVERT(varchar(16),DLP.DATA_HORA_PROCESSAMENTO,120), CONVERT(varchar(16),GETDATE(),120) ) <= 20
    AND DLP.STATUS = 'SUCESSO'
    AND DLP.NOME_ARQUIVO LIKE '%DE_PRICING_DR_PROPENSOS_CHURN%'
)    