SELECT
    X.ID_CLIENTE
    ,X.CPF
    ,X.DATA_HORA_VENDA AS DT_ULTIMA_COMPRA
    ,X.VALOR_TOTAL_NF
    ,X.ID_NF
FROM (
    SELECT
        PCR.ID_CLIENTE
        ,CCL.CPF
        ,NTH.DATA_HORA_VENDA
        ,NTH.VALOR_TOTAL_NF
        ,NTH.ID_NF
        ,row_number() over(partition by PCR.ID_CLIENTE order by NTH.DATA_HORA_VENDA desc) as RowNumber
        FROM DE_ALL_PROPENSOS_CHURN_RAIA PCR
        INNER JOIN DE_NOTA_HEADER_RAIA NTH
        ON PCR.ID_CLIENTE = NTH.ID_CLIENTE
        INNER JOIN DE_CAD_CLIENTE_RAIA CCL
        ON CCL.ID_CLIENTE = NTH.ID_CLIENTE
)X
WHERE RowNumber = 1