SELECT
    COUNT(PHR.ID_CLIENTE) AS VOLUME
    ,'VOLUME TOTAL' AS FILTRO
    ,GETDATE() AS DATA_CONSULTA
FROM DE_DH_TARGETING_PROPENSOS_CHURN_RAIA PHR

UNION 

SELECT
    COUNT(PHR.ID_CLIENTE) AS VOLUME
    ,'AGRUPAMENTO DOS ID_CLIENTES' AS FILTRO
    ,GETDATE() AS DATA_CONSULTA
FROM DE_PROPENSOS_CHURN_ID_CLIENTE_RAIA PHR

UNION 

SELECT
    COUNT(PHR.ID_CLIENTE) AS VOLUME
    ,'CRUZAMENTO CAD_CLIENTE' AS FILTRO
    ,GETDATE() AS DATA_CONSULTA
FROM DE_PROPENSOS_CHURN_ID_CLIENTE_RAIA PHR
INNER JOIN DE_CAD_CLIENTE_RAIA CCL
ON PHR.ID_CLIENTE = CCL.ID_CLIENTE

UNION 

SELECT
    COUNT(PHR.ID_CLIENTE) AS VOLUME
    ,'CRUZAMENTO DE_BOUNCES_BLACKLIST_RAIA' AS FILTRO
    ,GETDATE() AS DATA_CONSULTA
FROM DE_PROPENSOS_CHURN_ID_CLIENTE_RAIA PHR
INNER JOIN DE_CAD_CLIENTE_RAIA CCL
ON PHR.ID_CLIENTE = CCL.ID_CLIENTE
WHERE NOT EXISTS
(
    SELECT 1
    FROM DE_BOUNCES_BLACKLIST_RAIA BBR
    WHERE BBR.ID_CLIENTE = CCL.ID_CLIENTE
)

UNION 

SELECT
    COUNT(PHR.ID_CLIENTE) AS VOLUME
    ,'CRUZAMENTO COM A DO NOT CALL' AS FILTRO
    ,GETDATE() AS DATA_CONSULTA
FROM DE_PROPENSOS_CHURN_ID_CLIENTE_RAIA PHR
INNER JOIN DE_CAD_CLIENTE_RAIA CCL
ON PHR.ID_CLIENTE = CCL.ID_CLIENTE
WHERE NOT EXISTS
(
    SELECT 1
    FROM DE_BOUNCES_BLACKLIST_RAIA BBR
    WHERE BBR.ID_CLIENTE = CCL.ID_CLIENTE
)
AND NOT EXISTS
(
    SELECT 1
    FROM ENT.DE_CAD_DONOTCALL DCN
    WHERE DCN.DDD_TELEFONE = CCL.TEL_CELULAR
)

UNION 

SELECT
    COUNT(PHR.ID_CLIENTE) AS VOLUME
    ,'SEM DADOS CADASTRAIS' AS FILTRO
    ,GETDATE() AS DATA_CONSULTA
FROM DE_PROPENSOS_CHURN_ID_CLIENTE_RAIA PHR
INNER JOIN DE_CAD_CLIENTE_RAIA CCL
ON PHR.ID_CLIENTE = CCL.ID_CLIENTE
WHERE NOT EXISTS
(
    SELECT 1
    FROM DE_BOUNCES_BLACKLIST_RAIA BBR
    WHERE BBR.ID_CLIENTE = CCL.ID_CLIENTE
)
AND NOT EXISTS
(
    SELECT 1
    FROM ENT.DE_CAD_DONOTCALL DCN
    WHERE DCN.DDD_TELEFONE = CCL.TEL_CELULAR
)
AND (CCL.EMAIL IS NOT NULL OR CCL.TEL_CELULAR IS NOT NULL)

UNION

SELECT
    COUNT(PHR.ID_CLIENTE) AS VOLUME
    ,'CRUZAMENTO DE_BLACKLIST_SF_RAIA' AS FILTRO
    ,GETDATE() AS DATA_CONSULTA
FROM DE_PROPENSOS_CHURN_ID_CLIENTE_RAIA PHR
INNER JOIN DE_CAD_CLIENTE_RAIA CCL
ON PHR.ID_CLIENTE = CCL.ID_CLIENTE
WHERE NOT EXISTS
(
    SELECT 1
    FROM DE_BOUNCES_BLACKLIST_RAIA BBR
    WHERE BBR.ID_CLIENTE = CCL.ID_CLIENTE
)
AND NOT EXISTS
(
    SELECT 1
    FROM ENT.DE_CAD_DONOTCALL DCN
    WHERE DCN.DDD_TELEFONE = CCL.TEL_CELULAR
)
AND (CCL.EMAIL IS NOT NULL OR CCL.TEL_CELULAR IS NOT NULL)
AND NOT EXISTS
(
    SELECT 1
    FROM ENT.DE_BLACKLIST_SF_RAIA BLC
    WHERE BLC.ID_CLIENTE = CCL.ID_CLIENTE
)