SELECT CCL.ID_CLIENTE
      ,CCL.EMAIL
      ,CCL.TEL_CELULAR
      ,CCL.NOME
      ,'PT-BR' as LOCALE
      ,CCL.FILIAL_CADASTRO
      ,CONVERT(VARCHAR(10), GETDATE(), 101) AS DT_JOURNEY
FROM ENT.DE_SEGMENTACAO_DH_DNA SDN
INNER JOIN DE_CAD_CLIENTE_RAIA CCL
ON SDN.ID_CLIENTE = CCL.ID_CLIENTE
WHERE SDN.CD_TP_SEGMENTACAO = 140
AND (CCL.EMAIL IS NOT NULL OR CCL.TEL_CELULAR IS NOT NULL)
AND NOT EXISTS
(
    SELECT 1
    FROM DE_ALL_EX_FIEL_RAIA AEX
    WHERE AEX.ID_CLIENTE = CCL.ID_CLIENTE
)
AND NOT EXISTS
(
    SELECT 1
    FROM DE_BOUNCES_BLACKLIST_RAIA BBR
    WHERE BBR.ID_CLIENTE = CCL.ID_CLIENTE
)