SELECT
    X.ID_CLIENTE
    ,X.DATA_HORA_VENDA AS DT_ULTIMA_COMPRA
    ,X.VALOR_TOTAL_NF
    ,X.ID_NF
    ,X.CD_TELEVENDA
FROM (
    SELECT
        CMR.ID_CLIENTE
        ,NTH.DATA_HORA_VENDA
        ,NTH.VALOR_TOTAL_NF
        ,NTH.ID_NF
        ,NTH.CD_TELEVENDA
        ,row_number() over(partition by CMR.ID_CLIENTE order by NTH.DATA_HORA_VENDA desc) as RowNumber
        FROM DE_ALL_POTENCIAIS_DIGITAIS_RAIA CMR /*TROCAR PARA DE DE DROGASIL*/
        INNER JOIN DE_NOTA_HEADER_RAIA NTH /*TROCAR PARA DE DE DROGASIL*/
        ON CMR.ID_CLIENTE = NTH.ID_CLIENTE 
        INNER JOIN DE_TELEVENDA_RAIA DTR
        ON DTR.CD_TELEVENDA = NTH.CD_TELEVENDA
        WHERE NTH.CD_TELEVENDA IS NOT NULL 
        AND NTH.CD_TELEVENDA != 0
)X
WHERE RowNumber = 1