SELECT TOP 136776
    GM2.EMAIL as EMAIL
    ,GM2.ID_CLIENTE AS ID_CLIENTE
    ,GM2.DOMINIO AS DOMINIO
    ,'5' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+27) as DATA_WARM
FROM FLT_RAIA_GMAIL_SHABIT GM2
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_RAIA_JOURNEY JR
    WHERE JR.EMAIL = GM2.EMAIL
)

UNION

SELECT TOP 80000
    MF2.EMAIL as EMAIL
    ,MF2.ID_CLIENTE AS ID_CLIENTE
    ,MF2.DOMINIO AS DOMINIO
    ,'5' as TEMPLATE
    ,CONVERT(DATE, GETDATE()+27) as DATA_WARM
FROM FLT_RAIA_MICROSOFT_SHABIT MF2
WHERE NOT EXISTS
(
    SELECT JR.EMAIL
    FROM DE_WARMUP_RAIA_JOURNEY JR
    WHERE JR.EMAIL = MF2.EMAIL
)
