SELECT A1.GOLDEN_ID
,A1.ID_CLIENTE
,A1.BANDEIRA
,A1.CARTAO
,A1.EMPRESA
,A1.TIPO_CADASTRO
,A1.FILIAL_CADASTRO
,A1.DATA_CADASTRO
,A1.DT_ULTIMA_ATUALIZ
,A1.CD_FILIAL_FREQ
,A2.DT_ULTIMA_COMPRA
,A1.OPTIN
,A1.CPF
,A1.NOME
,A1.SOBRENOME
,A1.DATA_NASC
,A1.SEXO
,A1.ENDERECO
,A1.NR_ENDERECO
,A1.COMPLEMENTO
,A1.BAIRRO
,A1.CEP
,A1.CIDADE
,A1.UF
,A1.LOCALE
,A1.TEL_FIXO_RES
,A1.OPTOUT_TEL_FIXO_RES
,A1.TEL_FIXO_CML
,A1.OPTOUT_TEL_FIXO_CML
,A1.TEL_CELULAR
,A1.OPTOUT_TEL_CELULAR
,A1.EMAIL
,A1.OPTOUT_EMAIL
,A1.APP
,A1.FILIAL_FREQ_LOG 
FROM DE_CAD_CLIENTE_RAIA A1
INNER JOIN DE_CAD_CLIENTE_RAIA_IMPORT A2
ON A1.ID_CLIENTE = A2.ID_CLIENTE